apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-apache-deployment
  namespace: canary
  labels:
    app: apache
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      version: canary
  template:
    metadata:
      labels:
        app: webapp
        version: canary
    spec:
      containers:
      - image: prince511/apache-green:v1
        name: canary-apache
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
