apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-canary-deployment
  namespace: canary
  labels:
    app: nginx
    version: stable

spec:
  replicas: 4

  selector:
    matchLabels:
      app: webapp
      version: stable


  template:
    metadata:
      labels:
        app: webapp
        version: stable

    spec:
      containers:
      - name: nginx-canary-container
        image: prince511/nginx-blue:v1
        ports:
        - containerPort: 80
